services:
  mysql_tpv:
    image: mysql:8.0
    container_name: mysql_tpv_2025
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: gastos_ia
    ports:
      - "3308:3306"
    volumes:
      - mysql_tpv_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_tpv:
    image: redislabs/redisearch:latest
    container_name: redis_tpv_cache
    command:
      - redis-server
      - --requirepass
      - "Redis2024*"
      - --loadmodule
      - /usr/lib/redis/modules/redisearch.so
    ports:
      - "6381:6379"
    volumes:
      - redis_tpv_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Redis2024*", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_tpv_data:
  redis_tpv_data: